project:
  name: quickstart-cribl-logstream
  owner: quickstart-eng@amazon.com
  package_lambda: false
  parameters: 
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "$[taskcat_current_region]"
      webAccessCidr: 0.0.0.0/0
tests:
  cribl-deploy-new-vpc-arm:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
      VPCCIDR: 10.0.0.0/16
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      VPCTenancy: default
    template: templates/cribl-single-arm64-new-vpc.template.yaml
    regions:
      - us-west-1
  cribl-deploy-new-vpc-logging-arm:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
      VPCCIDR: 10.0.0.0/16
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      VPCTenancy: default
      LogFilePrefix: cribl-vpc-logs
      TrafficType: ALL
      SQS: cribl-sqs-vpc-logs-arm
    template: templates/cribl-single-arm64-new-vpc-logging.template.yaml
    regions:
      - us-west-2
  cribl-deploy-new-vpc-x86:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
      VPCCIDR: 10.0.0.0/16
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      VPCTenancy: default
    template: templates/cribl-single-x86-new-vpc.template.yaml
    regions:
      - us-east-1
  cribl-deploy-new-vpc-logging-x86:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
      VPCCIDR: 10.0.0.0/16
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      VPCTenancy: default
      LogFilePrefix: cribl-vpc-logs
      TrafficType: ALL
      SQS: cribl-sqs-vpc-logs-x86
    template: templates/cribl-single-x86-new-vpc-logging.template.yaml
    regions:
      - us-east-2